### ISSUE TITLE
HTTP/2 Push

### ISSUE THREAD

**Issue by derevandal** [bazzite/nuxt-netlify#1]
**Describe the solution you'd like**
Enables HTTP/2 server push on Netlify by `resources` config.

**Describe alternatives you've considered**
I'm using [this alternative](https://github.com/jmblog/nuxt-netlify-http2-server-push)

**Comment by juliomrqz** [comment]
Hi @derevandal. What's wrong with https://github.com/jmblog/nuxt-netlify-http2-server-push? Cannot be used with https://github.com/bazzite/nuxt-netlify?

**Comment by derevandal** [comment]
Hi, sorry for not respond.
Both manage to live peacefully.
